In [2]:
import pandas as pd

from pandas import Series, DataFrame

In [11]:
import numpy as np

# Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'a', 'b', 'c'])
obj2.index

Index(['d', 'a', 'b', 'c'], dtype='object')

In [7]:
obj2['a']

7

In [8]:
obj2['d'] = 6

obj2[['c', 'a', 'd']]

c    3
a    7
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
a    7
c    3
dtype: int64

In [10]:
obj2 * 2

d    12
a    14
b   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
a    1096.633158
b       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
sdata = {"Ohio" : 35000, "Texas" : 71000, "Oregon" : 16000, "Utah" : 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
states = ['California', 'Ohio', 'Texas', 'Oregon']

obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
dtype: float64

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Texas         False
Oregon        False
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Texas         False
Oregon        False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Texas          True
Oregon         True
dtype: bool

In [28]:
print(obj3.dtype), print(obj4.dtype)

int64
float64


(None, None)

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
Name: population, dtype: float64

# DataFrame

In [31]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002, 2003],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2] }

fname = pd.DataFrame(data)

fname

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
fname.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
fname2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'], index = ['one', 'two', 'three', 'four', 'five', 'six'])
fname2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [36]:
fname2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
fname2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [38]:
fname2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [39]:
fname2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [40]:
fname2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [41]:
fname2['debt'] = 16.5
fname2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
fname2['debt'] = np.arange(6.)
fname2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [45]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
fname2['debt'] = val

fname2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [52]:
fname2['eastern'] = fname2['state'] == 'Ohio'
fname2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [53]:
fname2['eastern'] = fname2.state == 'Ohio'
fname2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [54]:
del fname2['eastern']
fname2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [55]:
pop = {'Nevada' : {2001 : 2.4, 2002 : 2.9}, 'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}}
fname3 = DataFrame(pop)
fname3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
fname3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [58]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio' : fname3['Ohio'][:1], 'Nevada' : fname3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   NaN     2.9

In [62]:
fname3.index.name = 'year' ; fname3.columns.name = 'state'
fname3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
fname3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [64]:
fname2.values #서로 다른 dtype을 가지고 있는 경우, 모든 컬럼을 수용하기 위해, 그 컬럼의 배열의 dtype이 선택됨

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# pandas 핵심 기능

## reindex

In [65]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [67]:
obj.reindex([3,1,2,0])

3    3
1    7
2   -5
0    4
dtype: int64

In [69]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [70]:
obj3.reindex(range(6), method = 'ffill') #누락된 값을 직전의 값으로 채워넣음

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

## drop

In [73]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [72]:
new = obj.drop(0)
new

1    7
2   -5
3    3
dtype: int64

In [74]:
obj.drop([0,2])

1    7
3    3
dtype: int64

In [77]:
fname3.drop(2001)

state  Nevada  Ohio
year               
2002      2.9   3.6
2000      NaN   1.5

In [78]:
fname3.drop('Ohio',axis=1)

state  Nevada
year         
2001      2.4
2002      2.9
2000      NaN

In [79]:
fname3.drop('Ohio',axis='columns')

state  Nevada
year         
2001      2.4
2002      2.9
2000      NaN

## 색인

In [80]:
obj = pd.Series(np.arange(4.0), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [81]:
obj['b']

1.0

In [82]:
obj[2]

2.0

In [83]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [85]:
obj[['b','a','c']]

b    1.0
a    0.0
c    2.0
dtype: float64

In [86]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [87]:
obj[obj<3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [88]:
obj['b':'c'] #라벨 이름으로 하면 끝점 포함

b    1.0
c    2.0
dtype: float64

In [91]:
fname.loc[0,['year','pop']]

year    2000
pop      1.5
Name: 0, dtype: object

In [93]:
fname.iloc[2,[2,0,1]]

pop       3.6
state    Ohio
year     2002
Name: 2, dtype: object

In [94]:
fname.iloc[2]

state    Ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [95]:
fname.iloc[[1,2],[2,0,1]]

pop state  year
1  1.7  Ohio  2001
2  3.6  Ohio  2002

In [97]:
fname.loc[:3,'state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
Name: state, dtype: object

In [100]:
fname.iloc[:, :2][fname.year > 2001]

state  year
2    Ohio  2002
4  Nevada  2002
5  Nevada  2003

In [101]:
ser = Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [102]:
ser[-1]

KeyError: -1

In [103]:
ser2 = Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [104]:
ser2[:1]

a    0.0
dtype: float64

In [105]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [106]:
ser.iloc[:1]

0    0.0
dtype: float64

## 연산 및 데이터 정리

In [107]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

s1 + s2 #겹치면 값 출력, 안 겹치면 NaN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [108]:
df1 = DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [111]:
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd') )
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde') )

df2.loc[1,'b']

6.0

In [112]:
df2.loc[1,'b'] = np.nan

In [113]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [114]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [115]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [116]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [117]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [118]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [119]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [120]:
arr = np.arange(12.).reshape((3,4))
arr[0]

array([0., 1., 2., 3.])

In [122]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [121]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [123]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

series = df2.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [124]:
df2 - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [126]:
series2 = Series(range(3), index=['b','e','f'])

df2 + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [128]:
df2['d']

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [129]:
df2.sub(df2['d'], axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [130]:
df2.sub(df2['d'], axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 함수 적용, 매핑

In [139]:
df2 = DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b         d         e
Utah   -0.304195 -2.903776 -0.645398
Ohio   -1.188218  1.137449 -0.839916
Texas  -0.143541 -1.835256 -0.342767
Oregon -0.375760 -1.476994 -0.364868

In [140]:
np.abs(df2)

b         d         e
Utah    0.304195  2.903776  0.645398
Ohio    1.188218  1.137449  0.839916
Texas   0.143541  1.835256  0.342767
Oregon  0.375760  1.476994  0.364868

In [141]:
f = lambda x: x.max() -x.min()

df2.apply(f)

b    1.044677
d    4.041226
e    0.497148
dtype: float64

In [142]:
df2.apply(f,axis='columns')

Utah      2.599581
Ohio      2.325667
Texas     1.691715
Oregon    1.112126
dtype: float64

In [146]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min','max'])

df2.apply(f)

b         d         e
min -1.188218 -2.903776 -0.839916
max -0.143541  1.137449 -0.342767

In [148]:
df2

b         d         e
Utah   -0.304195 -2.903776 -0.645398
Ohio   -1.188218  1.137449 -0.839916
Texas  -0.143541 -1.835256 -0.342767
Oregon -0.375760 -1.476994 -0.364868

In [147]:
format2 = lambda x: '%.2f' % x
df2.applymap(format2)

b      d      e
Utah    -0.30  -2.90  -0.65
Ohio    -1.19   1.14  -0.84
Texas   -0.14  -1.84  -0.34
Oregon  -0.38  -1.48  -0.36

In [152]:
df2.map(format2) #DataFrame이라서 map이 적용 안됨 #Series로 되야지 map 적용 가능

AttributeError: 'DataFrame' object has no attribute 'map'

In [150]:
df2['e'].map(format2)

Utah      -0.65
Ohio      -0.84
Texas     -0.34
Oregon    -0.36
Name: e, dtype: object

## 정렬, 순위

In [155]:
obj2

d    6
a    7
b   -5
c    3
dtype: int64

In [154]:
obj2.sort_index()

a    7
b   -5
c    3
d    6
dtype: int64

In [156]:
fname

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [157]:
fname = DataFrame(np.arange(8).reshape((2,4)), columns=list('dabc'), index=['three','one'])
fname.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [158]:
fname.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [159]:
fname.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [162]:
obj2.sort_values()

b   -5
c    3
d    6
a    7
dtype: int64

In [164]:
fname.sort_values(by='b')

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [165]:
fname.sort_values(by=['b','a'])

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [167]:
obj2

d    6
a    7
b   -5
c    3
dtype: int64

In [166]:
obj2.rank()

d    3.0
a    4.0
b    1.0
c    2.0
dtype: float64

In [169]:
obj3 = pd.Series([7,-5,7,4,2,0,4])

obj3.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [170]:
obj3.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [171]:
obj3.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [172]:
obj3.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [174]:
df2.rank(axis='columns')

b    d    e
Utah    3.0  1.0  2.0
Ohio    1.0  3.0  2.0
Texas   3.0  1.0  2.0
Oregon  2.0  1.0  3.0

## 중복 색인

In [175]:
kkk = pd.Series(range(5), index=['a', 'b', 'a', 'b', 'c'])

kkk.index.is_unique

False

In [177]:
kkk.index.unique()

Index(['a', 'b', 'c'], dtype='object')

In [178]:
kkk['a']

a    0
a    2
dtype: int64

# 기술 통계 계산

sum, mean, cumsum, describe, count 등

axis, skipna, level

In [182]:
import pandas_datareader.data as web

In [184]:
all_data = {ticker : web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

all_data.items()

dict_items([('AAPL',                   High         Low        Open       Close       Volume  \
Date                                                                      
2015-03-04  129.559998  128.320007  129.100006  128.539993   31666300.0   
2015-03-05  128.750000  125.760002  128.580002  126.410004   56517100.0   
2015-03-06  129.369995  126.260002  128.399994  126.599998   72842100.0   
2015-03-09  129.570007  125.059998  127.959999  127.139999   88528500.0   
2015-03-10  127.220001  123.800003  126.410004  124.510002   68856600.0   
...                ...         ...         ...         ...          ...   
2020-02-25  302.529999  286.130005  300.950012  288.079987   57668400.0   
2020-02-26  297.880005  286.500000  286.529999  292.649994   49513700.0   
2020-02-27  286.000000  272.959991  281.100006  273.519989   80151400.0   
2020-02-28  278.410004  256.369995  257.260010  273.359985  106721200.0   
2020-03-02  301.440002  277.720001  282.279999  298.809998   85160300.0   

   

In [185]:
price = pd.DataFrame( {ticker : data['Adj Close']
                      for ticker, data in all_data.items() })
price.head()

AAPL         IBM       MSFT        GOOG
Date                                                     
2015-03-04  118.290138  128.027969  38.826534  571.800110
2015-03-05  116.330009  129.441391  38.871628  573.754761
2015-03-06  116.504845  127.289124  38.195362  566.130676
2015-03-09  117.001801  129.112137  38.637188  567.292480
2015-03-10  114.581505  126.735023  37.897800  553.490417

In [187]:
volumne = pd.DataFrame( {ticker : data['Volume']
                      for ticker, data in all_data.items() })
volumne.head()

AAPL        IBM        MSFT       GOOG
Date                                                    
2015-03-04  31666300.0  3633600.0  25748700.0  1876800.0
2015-03-05  56517100.0  3791700.0  23193500.0  1389600.0
2015-03-06  72842100.0  4540200.0  36248800.0  1659100.0
2015-03-09  88528500.0  5193900.0  32108000.0  1062100.0
2015-03-10  68856600.0  4601000.0  39159700.0  1792300.0

In [202]:
returns = price.pct_change() #퍼센트 변화율
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2015-03-04       NaN       NaN       NaN       NaN
2015-03-05 -0.016571  0.011040  0.001161  0.003418
2015-03-06  0.001503 -0.016627 -0.017397 -0.013288
2015-03-09  0.004266  0.014322  0.011568  0.002052
2015-03-10 -0.020686 -0.018411 -0.019137 -0.024330
...              ...       ...       ...       ...
2020-02-25 -0.033872 -0.032234 -0.016502 -0.023312
2020-02-26  0.015864 -0.013831  0.012495  0.003407
2020-02-27 -0.065368 -0.047513 -0.070459 -0.053898
2020-02-28 -0.000585 -0.022237  0.024213  0.016114
2020-03-02  0.093101  0.031886  0.066539  0.037168

[1258 rows x 4 columns]

In [203]:
returns['MSFT'].corr(returns['IBM'])

0.4785579510830447

In [204]:
returns['MSFT'].cov(returns['IBM'])

9.339898240363586e-05

In [205]:
returns.MSFT.corr(returns.IBM)

0.4785579510830447

In [206]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.405479  0.603504  0.549772
IBM   0.405479  1.000000  0.478558  0.418719
MSFT  0.603504  0.478558  1.000000  0.683353
GOOG  0.549772  0.418719  0.683353  1.000000

In [207]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000254  0.000085  0.000142  0.000134
IBM   0.000085  0.000174  0.000093  0.000084
MSFT  0.000142  0.000093  0.000219  0.000154
GOOG  0.000134  0.000084  0.000154  0.000232

In [208]:
returns.corrwith(returns.IBM)

AAPL    0.405479
IBM     1.000000
MSFT    0.478558
GOOG    0.418719
dtype: float64

In [210]:
returns.corrwith(volumne)

AAPL   -0.145821
IBM    -0.091311
MSFT   -0.039944
GOOG   -0.024430
dtype: float64

In [211]:
obj = pd.Series(['c','a','a','b','c','d','c','c'])

obj.unique()

array(['c', 'a', 'b', 'd'], dtype=object)

In [212]:
obj.value_counts()

c    4
a    2
b    1
d    1
dtype: int64

In [213]:
pd.value_counts(obj.values, sort=False)

c    4
a    2
d    1
b    1
dtype: int64

In [214]:
obj.isin(['b','c'])

0     True
1    False
2    False
3     True
4     True
5    False
6     True
7     True
dtype: bool

In [216]:
obj[ obj.isin(['b','c'])==True ]

0    c
3    b
4    c
6    c
7    c
dtype: object

In [217]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_val = pd.Series(['c', 'b', 'a'])

pd.Index(unique_val).get_indexer(to_match) #unique_val의 위치를 to_match에 적용

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [222]:
data = pd.DataFrame( {'Qu1' : [1,3,4,3,4],
                      'Qu2' : [2,3,1,2,3],
                      'Qu3' : [1,5,2,4,4]} )
result = data.apply(pd.value_counts)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [223]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0